# config.yaml
# 戦略パラメータ設定ファイル (YAML形式)
# このファイルに全ての戦略パラメータを定義する必要があります。

General:
  # INITIAL_CAPITAL と RISK_PER_TRADE は backtest_fw.py (base.py) のグローバル設定が優先されます。
  # ここでの定義は、将来的に戦略ごとに変更したい場合のプレースホルダーです。
  # INITIAL_CAPITAL: 70000000
  # RISK_PER_TRADE: 0.005
  execution_interval_minutes: 1
  context_interval_minutes: 5

EMA_Settings: # EMA関連の設定
  CONTEXT_PERIOD_SHORT_GC: 9
  CONTEXT_PERIOD_LONG_GC: 20
  SHORT_EXEC_CHART: 9      # 実行足チャート用 短期EMA
  LONG_EXEC_CHART: 20       # 実行足チャート用 長期EMA

ADX_Settings: # ADX関連の設定
  CONTEXT_PERIOD: 14
  CONTEXT_THRESHOLD: 18.0

STOCH_Settings: # ストキャスティクス関連の設定
  K_EXEC: 5
  D_EXEC: 3
  SMOOTH_EXEC: 3
  OVERBOUGHT_LEVEL: 70.0
  OVERSOLD_LEVEL: 30.0

MACD_Settings: # MACD関連の設定
  FAST_EXEC: 12
  SLOW_EXEC: 26
  SIGNAL_EXEC: 9
  HIST_EMA_PERIOD_EXEC: 5  # MACDヒストグラムのEMA期間 (実行足) <--- 追加

BB_Settings: # ボリンジャーバンド関連の設定
  PERIOD_CTX: 20
  NBDEV_CTX: 2.0
  PERIOD_EXEC: 20
  NBDEV_EXEC: 2.0

ATR_Settings: # ATR関連の設定
  PERIOD_CONTEXT: 14        # 環境足ATR期間 (チャート表示用)
  PERIOD_EXEC: 10           # 実行足ATR期間 (チャート表示用)
  STOP_PERIOD_CONTEXT: 14   # ATR損切りに使用する環境足ATRの期間

SMA_Settings: # SMA関連の設定
  CONTEXT_PERIOD_1: 50
  CONTEXT_PERIOD_2: 200
  EXEC_PERIOD_1: 50
  EXEC_PERIOD_2: 200

Activation_Flags: # 各種ロジックの有効化フラグ
  # 環境認識フェーズ (0:無効, 1:OR条件, 2:AND条件)
  CONTEXT_TREND_DIR_EMA_CROSS_ACTIVE: 2
  CONTEXT_TREND_STR_ADX_ACTIVE: 2

  # エントリーフェーズ (0:無効, 1:OR条件, 2:AND条件)
  ENTRY_STOCH_ACTIVE: 2
  ENTRY_MACD_ACTIVE: 2
  ENTRY_BB_MIDDLE_ACTIVE: 2
  ENTRY_MACD_HIST_EMA_ACTIVE: 0      # MACDヒストグラムEMAでのエントリー (0:無効, 1:OR条件, 2:AND条件) <--- 追加

  # 決済ロジック (0:無効, 1:有効)
  # 損切 (Stop Loss)
  STOP_LOSS_STOCH_REVERSE_ACTIVE: 1
  STOP_LOSS_MACD_REVERSE_ACTIVE: 1
  STOP_LOSS_BB_MIDDLE_REVERSE_ACTIVE: 1
  STOP_LOSS_ATR_MULTIPLE: 0 #2.0       # ATR SLの倍率 (0以下またはコメントアウトで無効)
  STOP_LOSS_MACD_HIST_EMA_REVERSE_ACTIVE: 1 # MACDヒストグラムEMAのクロス/傾き反転での損切り <--- 追加

  # 利確 (Take Profit)
  TAKE_PROFIT_STOCH_EXTREME_REVERSE_ACTIVE: 0
  TAKE_PROFIT_MACD_HIST_REVERSE_ACTIVE: 1
  TAKE_PROFIT_BB_EXTREME_TOUCH_ACTIVE: 1
  TAKE_PROFIT_MACD_HIST_EMA_REVERSE_ACTIVE: 1 # MACDヒストグラムEMAの傾き反転での利確 <--- 追加

  # 強制決済
  STRATEGY_CONSIDERS_FORCE_EXIT_TIME: 0 # 1: 戦略がFWの強制決済時刻を考慮する

Trading_Hours: # 取引時間
  ENTRY_START_TIME_STR: '09:00:00'
  ENTRY_END_TIME_STR: '14:55:00'
  FORCE_EXIT_TIME_STR: '15:00:00'